#pragma once

// =============================================================================
// secp256k1_precomp.cuh — Precomputed generator multiples for secp256k1
// =============================================================================
//
// Table of 256 precomputed points: G, 2G, 4G, 8G, ..., 2^255 * G
// Each entry i holds 2^i * G in affine coordinates (mp_number x, y).
//
// Used by the init kernel for fixed-base scalar multiplication via
// a simple binary method: for each bit i of the private key, if set,
// add precomp[i] to the accumulator.
//
// Format: arrays of secp256k1_point indexed by bit position [0..255].
// Entry 0 = G, entry 1 = 2G, entry 2 = 4G, etc.
//
// NOTE: This header declares the table as extern. The actual table data
// is generated by tools/gen_precomp_secp256k1.py and loaded at runtime,
// or compiled from a generated .cu file. For now we provide the first
// few entries and the generator point inline; the init kernel computes
// the rest via repeated doubling during the first launch.
//
// Dependencies: secp256k1_ops.cuh (for secp256k1_point, mp_number)
// =============================================================================

#include "secp256k1_ops.cuh"

// Number of precomputed points (one per bit of the 256-bit scalar)
#define SECP256K1_PRECOMP_SIZE 256

// The precomputed table lives in device constant memory for fast access.
// It is populated by the init kernel on first launch via point doubling.
// The host copies the generated table to this symbol before kernel launch.
extern __device__ __constant__ secp256k1_point d_secp256k1_precomp[SECP256K1_PRECOMP_SIZE];

// Host-side storage for the precomputed table (filled by host, copied to device)
// Declared in secp256k1_init.cu
