// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: hyperfanity.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	GpuCount      int32                  `protobuf:"varint,2,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuNames      []string               `protobuf:"bytes,3,rep,name=gpu_names,json=gpuNames,proto3" json:"gpu_names,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_hyperfanity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *RegisterRequest) GetGpuNames() []string {
	if x != nil {
		return x.GpuNames
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_hyperfanity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	WorkerId        string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token           string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	SupportedChains []string               `protobuf:"bytes,3,rep,name=supported_chains,json=supportedChains,proto3" json:"supported_chains,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetJobRequest) Reset() {
	*x = GetJobRequest{}
	mi := &file_hyperfanity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobRequest) ProtoMessage() {}

func (x *GetJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobRequest.ProtoReflect.Descriptor instead.
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{2}
}

func (x *GetJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetJobRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetJobRequest) GetSupportedChains() []string {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

type Job struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JobId           string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Chain           string                 `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Pattern         string                 `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	MatchType       string                 `protobuf:"bytes,4,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"` // "prefix", "suffix", "contains"
	MinScore        uint32                 `protobuf:"varint,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	SeedPubkey      []byte                 `protobuf:"bytes,6,opt,name=seed_pubkey,json=seedPubkey,proto3" json:"seed_pubkey,omitempty"`
	FullKeypairMode bool                   `protobuf:"varint,7,opt,name=full_keypair_mode,json=fullKeypairMode,proto3" json:"full_keypair_mode,omitempty"`
	PrefixChars     uint32                 `protobuf:"varint,8,opt,name=prefix_chars,json=prefixChars,proto3" json:"prefix_chars,omitempty"` // Number of chars to match from front
	SuffixChars     uint32                 `protobuf:"varint,9,opt,name=suffix_chars,json=suffixChars,proto3" json:"suffix_chars,omitempty"` // Number of chars to match from back
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_hyperfanity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{3}
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Job) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Job) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *Job) GetMinScore() uint32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *Job) GetSeedPubkey() []byte {
	if x != nil {
		return x.SeedPubkey
	}
	return nil
}

func (x *Job) GetFullKeypairMode() bool {
	if x != nil {
		return x.FullKeypairMode
	}
	return false
}

func (x *Job) GetPrefixChars() uint32 {
	if x != nil {
		return x.PrefixChars
	}
	return 0
}

func (x *Job) GetSuffixChars() uint32 {
	if x != nil {
		return x.SuffixChars
	}
	return 0
}

type ProgressUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	HashrateMhs   float64                `protobuf:"fixed64,3,opt,name=hashrate_mhs,json=hashrateMhs,proto3" json:"hashrate_mhs,omitempty"`
	TotalChecked  uint64                 `protobuf:"varint,4,opt,name=total_checked,json=totalChecked,proto3" json:"total_checked,omitempty"`
	BestScore     uint32                 `protobuf:"varint,5,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_hyperfanity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{4}
}

func (x *ProgressUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetHashrateMhs() float64 {
	if x != nil {
		return x.HashrateMhs
	}
	return 0
}

func (x *ProgressUpdate) GetTotalChecked() uint64 {
	if x != nil {
		return x.TotalChecked
	}
	return 0
}

func (x *ProgressUpdate) GetBestScore() uint32 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

type VanityResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PrivateKey    []byte                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Score         uint32                 `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Chain         string                 `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VanityResult) Reset() {
	*x = VanityResult{}
	mi := &file_hyperfanity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VanityResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VanityResult) ProtoMessage() {}

func (x *VanityResult) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VanityResult.ProtoReflect.Descriptor instead.
func (*VanityResult) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{5}
}

func (x *VanityResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *VanityResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *VanityResult) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *VanityResult) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *VanityResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VanityResult) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *VanityResult) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_hyperfanity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{6}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_hyperfanity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ShouldContinue bool                   `protobuf:"varint,1,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_hyperfanity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hyperfanity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_hyperfanity_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hyperfanity_proto protoreflect.FileDescriptor

const file_hyperfanity_proto_rawDesc = "" +
	"\n" +
	"\x11hyperfanity.proto\x12\vhyperfanity\"\x81\x01\n" +
	"\x0fRegisterRequest\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1b\n" +
	"\tgpu_count\x18\x02 \x01(\x05R\bgpuCount\x12\x1b\n" +
	"\tgpu_names\x18\x03 \x03(\tR\bgpuNames\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"E\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"m\n" +
	"\rGetJobRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12)\n" +
	"\x10supported_chains\x18\x03 \x03(\tR\x0fsupportedChains\"\x9b\x02\n" +
	"\x03Job\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05chain\x18\x02 \x01(\tR\x05chain\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\x12\x1d\n" +
	"\n" +
	"match_type\x18\x04 \x01(\tR\tmatchType\x12\x1b\n" +
	"\tmin_score\x18\x05 \x01(\rR\bminScore\x12\x1f\n" +
	"\vseed_pubkey\x18\x06 \x01(\fR\n" +
	"seedPubkey\x12*\n" +
	"\x11full_keypair_mode\x18\a \x01(\bR\x0ffullKeypairMode\x12!\n" +
	"\fprefix_chars\x18\b \x01(\rR\vprefixChars\x12!\n" +
	"\fsuffix_chars\x18\t \x01(\rR\vsuffixChars\"\xab\x01\n" +
	"\x0eProgressUpdate\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12!\n" +
	"\fhashrate_mhs\x18\x03 \x01(\x01R\vhashrateMhs\x12#\n" +
	"\rtotal_checked\x18\x04 \x01(\x04R\ftotalChecked\x12\x1d\n" +
	"\n" +
	"best_score\x18\x05 \x01(\rR\tbestScore\"\xc8\x01\n" +
	"\fVanityResult\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\fR\n" +
	"privateKey\x12\x1d\n" +
	"\n" +
	"public_key\x18\x04 \x01(\fR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x05 \x01(\tR\aaddress\x12\x14\n" +
	"\x05score\x18\x06 \x01(\rR\x05score\x12\x14\n" +
	"\x05chain\x18\a \x01(\tR\x05chain\"9\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"V\n" +
	"\x11HeartbeatResponse\x12'\n" +
	"\x0fshould_continue\x18\x01 \x01(\bR\x0eshouldContinue\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xe1\x02\n" +
	"\x12HyperfanityService\x12G\n" +
	"\bRegister\x12\x1c.hyperfanity.RegisterRequest\x1a\x1d.hyperfanity.RegisterResponse\x126\n" +
	"\x06GetJob\x12\x1a.hyperfanity.GetJobRequest\x1a\x10.hyperfanity.Job\x12A\n" +
	"\x0eReportProgress\x12\x1b.hyperfanity.ProgressUpdate\x1a\x10.hyperfanity.Ack(\x01\x12;\n" +
	"\fReportResult\x12\x19.hyperfanity.VanityResult\x1a\x10.hyperfanity.Ack\x12J\n" +
	"\tHeartbeat\x12\x1d.hyperfanity.HeartbeatRequest\x1a\x1e.hyperfanity.HeartbeatResponseB&Z$github.com/user/hyperfanity/panel/pbb\x06proto3"

var (
	file_hyperfanity_proto_rawDescOnce sync.Once
	file_hyperfanity_proto_rawDescData []byte
)

func file_hyperfanity_proto_rawDescGZIP() []byte {
	file_hyperfanity_proto_rawDescOnce.Do(func() {
		file_hyperfanity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperfanity_proto_rawDesc), len(file_hyperfanity_proto_rawDesc)))
	})
	return file_hyperfanity_proto_rawDescData
}

var file_hyperfanity_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_hyperfanity_proto_goTypes = []any{
	(*RegisterRequest)(nil),   // 0: hyperfanity.RegisterRequest
	(*RegisterResponse)(nil),  // 1: hyperfanity.RegisterResponse
	(*GetJobRequest)(nil),     // 2: hyperfanity.GetJobRequest
	(*Job)(nil),               // 3: hyperfanity.Job
	(*ProgressUpdate)(nil),    // 4: hyperfanity.ProgressUpdate
	(*VanityResult)(nil),      // 5: hyperfanity.VanityResult
	(*Ack)(nil),               // 6: hyperfanity.Ack
	(*HeartbeatRequest)(nil),  // 7: hyperfanity.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 8: hyperfanity.HeartbeatResponse
}
var file_hyperfanity_proto_depIdxs = []int32{
	0, // 0: hyperfanity.HyperfanityService.Register:input_type -> hyperfanity.RegisterRequest
	2, // 1: hyperfanity.HyperfanityService.GetJob:input_type -> hyperfanity.GetJobRequest
	4, // 2: hyperfanity.HyperfanityService.ReportProgress:input_type -> hyperfanity.ProgressUpdate
	5, // 3: hyperfanity.HyperfanityService.ReportResult:input_type -> hyperfanity.VanityResult
	7, // 4: hyperfanity.HyperfanityService.Heartbeat:input_type -> hyperfanity.HeartbeatRequest
	1, // 5: hyperfanity.HyperfanityService.Register:output_type -> hyperfanity.RegisterResponse
	3, // 6: hyperfanity.HyperfanityService.GetJob:output_type -> hyperfanity.Job
	6, // 7: hyperfanity.HyperfanityService.ReportProgress:output_type -> hyperfanity.Ack
	6, // 8: hyperfanity.HyperfanityService.ReportResult:output_type -> hyperfanity.Ack
	8, // 9: hyperfanity.HyperfanityService.Heartbeat:output_type -> hyperfanity.HeartbeatResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hyperfanity_proto_init() }
func file_hyperfanity_proto_init() {
	if File_hyperfanity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperfanity_proto_rawDesc), len(file_hyperfanity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hyperfanity_proto_goTypes,
		DependencyIndexes: file_hyperfanity_proto_depIdxs,
		MessageInfos:      file_hyperfanity_proto_msgTypes,
	}.Build()
	File_hyperfanity_proto = out.File
	file_hyperfanity_proto_goTypes = nil
	file_hyperfanity_proto_depIdxs = nil
}
