// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hyperfanity.proto

package pb

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const _ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)

type RegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string   `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	GpuCount int32    `protobuf:"varint,2,opt,name=gpu_count,json=gpuCount,proto3" json:"gpu_count,omitempty"`
	GpuNames []string `protobuf:"bytes,3,rep,name=gpu_names,json=gpuNames,proto3" json:"gpu_names,omitempty"`
	Version  string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetGpuCount() int32 {
	if x != nil {
		return x.GpuCount
	}
	return 0
}

func (x *RegisterRequest) GetGpuNames() []string {
	if x != nil {
		return x.GpuNames
	}
	return nil
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *RegisterResponse) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetJobRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId        string   `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token           string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	SupportedChains []string `protobuf:"bytes,3,rep,name=supported_chains,json=supportedChains,proto3" json:"supported_chains,omitempty"`
}

func (x *GetJobRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *GetJobRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetJobRequest) GetSupportedChains() []string {
	if x != nil {
		return x.SupportedChains
	}
	return nil
}

type Job struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId           string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Chain           string `protobuf:"bytes,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Pattern         string `protobuf:"bytes,3,opt,name=pattern,proto3" json:"pattern,omitempty"`
	MatchType       string `protobuf:"bytes,4,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	MinScore        uint32 `protobuf:"varint,5,opt,name=min_score,json=minScore,proto3" json:"min_score,omitempty"`
	SeedPubkey      []byte `protobuf:"bytes,6,opt,name=seed_pubkey,json=seedPubkey,proto3" json:"seed_pubkey,omitempty"`
	FullKeypairMode bool   `protobuf:"varint,7,opt,name=full_keypair_mode,json=fullKeypairMode,proto3" json:"full_keypair_mode,omitempty"`
}

func (x *Job) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *Job) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Job) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Job) GetMatchType() string {
	if x != nil {
		return x.MatchType
	}
	return ""
}

func (x *Job) GetMinScore() uint32 {
	if x != nil {
		return x.MinScore
	}
	return 0
}

func (x *Job) GetSeedPubkey() []byte {
	if x != nil {
		return x.SeedPubkey
	}
	return nil
}

func (x *Job) GetFullKeypairMode() bool {
	if x != nil {
		return x.FullKeypairMode
	}
	return false
}

type ProgressUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId     string  `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId        string  `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	HashrateMhs  float64 `protobuf:"fixed64,3,opt,name=hashrate_mhs,json=hashrateMhs,proto3" json:"hashrate_mhs,omitempty"`
	TotalChecked uint64  `protobuf:"varint,4,opt,name=total_checked,json=totalChecked,proto3" json:"total_checked,omitempty"`
	BestScore    uint32  `protobuf:"varint,5,opt,name=best_score,json=bestScore,proto3" json:"best_score,omitempty"`
}

func (x *ProgressUpdate) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *ProgressUpdate) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ProgressUpdate) GetHashrateMhs() float64 {
	if x != nil {
		return x.HashrateMhs
	}
	return 0
}

func (x *ProgressUpdate) GetTotalChecked() uint64 {
	if x != nil {
		return x.TotalChecked
	}
	return 0
}

func (x *ProgressUpdate) GetBestScore() uint32 {
	if x != nil {
		return x.BestScore
	}
	return 0
}

type VanityResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId   string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	JobId      string `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	PrivateKey []byte `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PublicKey  []byte `protobuf:"bytes,4,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address    string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Score      uint32 `protobuf:"varint,6,opt,name=score,proto3" json:"score,omitempty"`
	Chain      string `protobuf:"bytes,7,opt,name=chain,proto3" json:"chain,omitempty"`
}

func (x *VanityResult) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *VanityResult) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *VanityResult) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *VanityResult) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *VanityResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VanityResult) GetScore() uint32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *VanityResult) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Ack) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WorkerId string `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Token    string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HeartbeatRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShouldContinue bool   `protobuf:"varint,1,opt,name=should_continue,json=shouldContinue,proto3" json:"should_continue,omitempty"`
	Message        string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HeartbeatResponse) GetShouldContinue() bool {
	if x != nil {
		return x.ShouldContinue
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Ensure all types implement the protobuf message interface.
var (
	_ sync.Locker // prevent unused import
)
