// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// HyperfanityServiceClient is the client API for HyperfanityService service.
type HyperfanityServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error)
	ReportProgress(ctx context.Context, opts ...grpc.CallOption) (HyperfanityService_ReportProgressClient, error)
	ReportResult(ctx context.Context, in *VanityResult, opts ...grpc.CallOption) (*Ack, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type hyperfanityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperfanityServiceClient(cc grpc.ClientConnInterface) HyperfanityServiceClient {
	return &hyperfanityServiceClient{cc}
}

func (c *hyperfanityServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/hyperfanity.HyperfanityService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/hyperfanity.HyperfanityService/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) ReportProgress(ctx context.Context, opts ...grpc.CallOption) (HyperfanityService_ReportProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &HyperfanityService_ServiceDesc.Streams[0], "/hyperfanity.HyperfanityService/ReportProgress", opts...)
	if err != nil {
		return nil, err
	}
	x := &hyperfanityServiceReportProgressClient{stream}
	return x, nil
}

type HyperfanityService_ReportProgressClient interface {
	Send(*ProgressUpdate) error
	CloseAndRecv() (*Ack, error)
	grpc.ClientStream
}

type hyperfanityServiceReportProgressClient struct {
	grpc.ClientStream
}

func (x *hyperfanityServiceReportProgressClient) Send(m *ProgressUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hyperfanityServiceReportProgressClient) CloseAndRecv() (*Ack, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Ack)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hyperfanityServiceClient) ReportResult(ctx context.Context, in *VanityResult, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/hyperfanity.HyperfanityService/ReportResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, "/hyperfanity.HyperfanityService/Heartbeat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperfanityServiceServer is the server API for HyperfanityService service.
type HyperfanityServiceServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	GetJob(context.Context, *GetJobRequest) (*Job, error)
	ReportProgress(HyperfanityService_ReportProgressServer) error
	ReportResult(context.Context, *VanityResult) (*Ack, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedHyperfanityServiceServer should be embedded to have forward compatible implementations.
type UnimplementedHyperfanityServiceServer struct{}

func (UnimplementedHyperfanityServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHyperfanityServiceServer) GetJob(context.Context, *GetJobRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedHyperfanityServiceServer) ReportProgress(HyperfanityService_ReportProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedHyperfanityServiceServer) ReportResult(context.Context, *VanityResult) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedHyperfanityServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}

// UnsafeHyperfanityServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeHyperfanityServiceServer interface {
	mustEmbedUnimplementedHyperfanityServiceServer()
}

func RegisterHyperfanityServiceServer(s grpc.ServiceRegistrar, srv HyperfanityServiceServer) {
	s.RegisterService(&HyperfanityService_ServiceDesc, srv)
}

func _HyperfanityService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperfanity.HyperfanityService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperfanityService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperfanity.HyperfanityService/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

type HyperfanityService_ReportProgressServer interface {
	SendAndClose(*Ack) error
	Recv() (*ProgressUpdate, error)
	grpc.ServerStream
}

type hyperfanityServiceReportProgressServer struct {
	grpc.ServerStream
}

func (x *hyperfanityServiceReportProgressServer) SendAndClose(m *Ack) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hyperfanityServiceReportProgressServer) Recv() (*ProgressUpdate, error) {
	m := new(ProgressUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HyperfanityService_ReportProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyperfanityServiceServer).ReportProgress(&hyperfanityServiceReportProgressServer{stream})
}

func _HyperfanityService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VanityResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperfanity.HyperfanityService/ReportResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).ReportResult(ctx, req.(*VanityResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperfanityService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hyperfanity.HyperfanityService/Heartbeat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HyperfanityService_ServiceDesc is the grpc.ServiceDesc for HyperfanityService service.
var HyperfanityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperfanity.HyperfanityService",
	HandlerType: (*HyperfanityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _HyperfanityService_Register_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _HyperfanityService_GetJob_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _HyperfanityService_ReportResult_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HyperfanityService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportProgress",
			Handler:       _HyperfanityService_ReportProgress_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hyperfanity.proto",
}
