// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: hyperfanity.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HyperfanityService_Register_FullMethodName       = "/hyperfanity.HyperfanityService/Register"
	HyperfanityService_GetJob_FullMethodName         = "/hyperfanity.HyperfanityService/GetJob"
	HyperfanityService_ReportProgress_FullMethodName = "/hyperfanity.HyperfanityService/ReportProgress"
	HyperfanityService_ReportResult_FullMethodName   = "/hyperfanity.HyperfanityService/ReportResult"
	HyperfanityService_Heartbeat_FullMethodName      = "/hyperfanity.HyperfanityService/Heartbeat"
)

// HyperfanityServiceClient is the client API for HyperfanityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperfanityServiceClient interface {
	// Worker registers with the panel
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	// Worker requests a job
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error)
	// Worker streams progress updates
	ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, Ack], error)
	// Worker reports a vanity address result
	ReportResult(ctx context.Context, in *VanityResult, opts ...grpc.CallOption) (*Ack, error)
	// Worker heartbeat
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type hyperfanityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperfanityServiceClient(cc grpc.ClientConnInterface) HyperfanityServiceClient {
	return &hyperfanityServiceClient{cc}
}

func (c *hyperfanityServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, HyperfanityService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, HyperfanityService_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) ReportProgress(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ProgressUpdate, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyperfanityService_ServiceDesc.Streams[0], HyperfanityService_ReportProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ProgressUpdate, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyperfanityService_ReportProgressClient = grpc.ClientStreamingClient[ProgressUpdate, Ack]

func (c *hyperfanityServiceClient) ReportResult(ctx context.Context, in *VanityResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, HyperfanityService_ReportResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperfanityServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, HyperfanityService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperfanityServiceServer is the server API for HyperfanityService service.
// All implementations must embed UnimplementedHyperfanityServiceServer
// for forward compatibility.
type HyperfanityServiceServer interface {
	// Worker registers with the panel
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	// Worker requests a job
	GetJob(context.Context, *GetJobRequest) (*Job, error)
	// Worker streams progress updates
	ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, Ack]) error
	// Worker reports a vanity address result
	ReportResult(context.Context, *VanityResult) (*Ack, error)
	// Worker heartbeat
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedHyperfanityServiceServer()
}

// UnimplementedHyperfanityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHyperfanityServiceServer struct{}

func (UnimplementedHyperfanityServiceServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedHyperfanityServiceServer) GetJob(context.Context, *GetJobRequest) (*Job, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedHyperfanityServiceServer) ReportProgress(grpc.ClientStreamingServer[ProgressUpdate, Ack]) error {
	return status.Error(codes.Unimplemented, "method ReportProgress not implemented")
}
func (UnimplementedHyperfanityServiceServer) ReportResult(context.Context, *VanityResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportResult not implemented")
}
func (UnimplementedHyperfanityServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedHyperfanityServiceServer) mustEmbedUnimplementedHyperfanityServiceServer() {}
func (UnimplementedHyperfanityServiceServer) testEmbeddedByValue()                            {}

// UnsafeHyperfanityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperfanityServiceServer will
// result in compilation errors.
type UnsafeHyperfanityServiceServer interface {
	mustEmbedUnimplementedHyperfanityServiceServer()
}

func RegisterHyperfanityServiceServer(s grpc.ServiceRegistrar, srv HyperfanityServiceServer) {
	// If the following call panics, it indicates UnimplementedHyperfanityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HyperfanityService_ServiceDesc, srv)
}

func _HyperfanityService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperfanityService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperfanityService_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperfanityService_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperfanityService_ReportProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyperfanityServiceServer).ReportProgress(&grpc.GenericServerStream[ProgressUpdate, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HyperfanityService_ReportProgressServer = grpc.ClientStreamingServer[ProgressUpdate, Ack]

func _HyperfanityService_ReportResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VanityResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).ReportResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperfanityService_ReportResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).ReportResult(ctx, req.(*VanityResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperfanityService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperfanityServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperfanityService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperfanityServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HyperfanityService_ServiceDesc is the grpc.ServiceDesc for HyperfanityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyperfanityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hyperfanity.HyperfanityService",
	HandlerType: (*HyperfanityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _HyperfanityService_Register_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _HyperfanityService_GetJob_Handler,
		},
		{
			MethodName: "ReportResult",
			Handler:    _HyperfanityService_ReportResult_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _HyperfanityService_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportProgress",
			Handler:       _HyperfanityService_ReportProgress_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hyperfanity.proto",
}
